services:
  blinko-website:
    image: blinkospace/blinko:latest
    container_name: blinko-website
    environment:
      NODE_ENV: production
      # NEXTAUTH_URL: http://localhost:1111
      # IMPORTANT: If you want to use sso, you must set NEXTAUTH_URL to your own domain
      NEXT_PUBLIC_BASE_URL: ${NEXT_PUBLIC_BASE_URL}
      # IMPORTANT: Replace this with your own secure secret key!
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
      DATABASE_URL: postgresql://blinko:${POSTGRES_PASSWORD}@postgres:5432/blinko
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - blinko-website:/app/.blinko
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://blinko-website:1111/"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  postgres:
    image: postgres:14
    container_name: blinko-postgres
    restart: always
    environment:
      POSTGRES_DB: blinko
      POSTGRES_USER: blinko
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      TZ: America/Sao_Paulo
    volumes:
      - blinko-postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "blinko", "-d", "blinko"]
      interval: 5s
      timeout: 10s
      retries: 5
