services:
  baserow:
    container_name: baserow
    image: baserow/baserow:latest
    environment:
      BASEROW_PUBLIC_URL: ${BASEROW_PUBLIC_URL}
      WEB_FRONTEND_PORT: 3000
    ports:
      - "3000:3000"
    volumes:
      - baserow_data:/baserow/data
volumes:
  baserow_data: