services:
  baserow:
    container_name: baserow
    image: baserow/baserow:latest
    environment:
      BASEROW_PUBLIC_URL: ${BASEROW_PUBLIC_URL}
    volumes:
      - baserow_data:/baserow/data
volumes:
  baserow_data: