services:
    mediamtx:
        network_mode: host
        environment:
            - MTX_RTSPTRANSPORTS=tcp
            - MTX_WEBRTCADDITIONALHOSTS=192.168.100.109
        image: bluenviron/mediamtx
